[app_servers]
app_node_1 ansible_host=74.248.32.108 ansible_user=ia-admin

[db_servers]
db_node_1 ansible_host=74.248.17.65 ansible_user=ia-admin

[storage_servers]
app_node_1 ansible_host=74.248.32.108 ansible_user=ia-admin

[srodowisko_dev:children]
app_servers
db_servers
storage_servers

[app_servers:vars]
backend_port=1234
nginx_port=80

[db_servers:vars]
db_port=5432
env_type=development

[storage_servers:vars]
minio_port=9000
minio_console_port=9001
