# GRUPA 1: Serwery Bazodanowe
[db_servers]
db_node_1 ansible_host=74.248.130.50 ansible_user=delise2
#db_node_2 ansible_host=10.0.0.6 ansible_user=delise

# GRUPA 2: Serwery Aplikacyjne
[app_servers]
app_node_1 ansible_host=20.215.208.11 ansible_user=delise
#app_node_2 ansible_host=10.0.0.11 ansible_user=ubuntu
#app_node_3 ansible_host=10.0.0.12 ansible_user=ubunt

# GRUPA 3: Serwery Magazynowe (MinIO)
[storage_servers]
storage_node_1 ansible_host=20.215.208.11 ansible_user=delise

# METAGRUPA: całe środowisko developerskie
[srodowisko_dev:children]
db_servers
app_servers
storage_servers

# Zmienne dla PostgreSQL
[db_servers:vars]
db_port=5432
env_type=development

# Zmienne dla MinIO
[storage_servers:vars]
minio_port=9000
minio_console_port=9001

# Zmienne dla aplikacji
[app_servers:vars]
backend_port=5000
nginx_port=80
